services:
  mysql:
    container_name: mysql-idp
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      PGDATA: /data/mysql-idp-vol
      MYSQL_DATABASE: idp_mysql
    volumes:
      - mysql-idp-vol:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped

  phpmyadmin: # must connect to host 172.17.0.2:3306
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8089:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mysql

networks:
  mysql:
    driver: bridge

volumes:
  mysql-idp-vol:
  pgadmin: