spring:
  datasource:
    url: jdbc:mysql://localhost:3306/idp_mysql
#    url: jdbc:mysql://mysql-idp:3306/idp_mysql
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        format_sql: true
  application:
    name: IDP-Business-Logic-Service
  sql:
    init:
      continue-on-error: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  error:
    include-message: always
  port: 8081

authServerUrl: http://localhost:8083
#authServerUrl: http://idp-auth-service:8083

#logging:
#  level:
#    root: DEBUG